version: '2.1'

volumes:
  postgres_data:
  cass_data:
  zoo_data:
  broker_data:

services:
  backend_app:
    image: irania9o/synapse_backend:latest
    container_name: 'backend_app'
    restart: always
    ports:
      - 8080:8080
    environment:
      - postgres_address=postgres_backend
      - postgres_port=5432
      - mongo_address=mongo
      - mongo_port=27017
    deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5
        resources:
            limits:
              memory: 200M
  postgres_backend:
    image: postgres:alpine3.19
    volumes:
     - postgres_data:/var
    restart: always
    container_name: 'postgres_backend'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      resources:
        limits:
          memory: 200M
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false